### ISSUE TITLE
When switching from Blender to other applications the widgets with images in them will turn Black.

### ISSUE THREAD

**Issue by antonyjones67** [jayanam/bl_ui_widgets#1]
NVIDIA Geoforce 1060 GTX
Driver version 430.39

![image](https://user-images.githubusercontent.com/3905646/57185859-113c7980-6e91-11e9-872c-826dc48a4ac2.png)

When switching from Blender to other applications the widgets with images in them will turn Black.

If you hit Ctrl-Shift-F again it fixes the images in the widgets.

Would be grateful for any ideas. Thank you.

**Comment by antonio-ginestar** [comment]
Same here but without switching to other applications. Tried to debug but I cant find the root of the problem. The buttons' images turn black randomly when using the program.

**Comment by antonio-ginestar** [comment]
Found the error, simply put self.__image.gl_touch() inside the try case in the BL_UI_Button.draw_image function. 
https://docs.blender.org/api/current/bpy.types.Image.html?highlight=gl_touch#bpy.types.Image.gl_touch

**Comment by vilemduha** [comment]
Why was this closed? clearly happens in recent versions
