### ISSUE TITLE
Mouse enter/exit functions

### ISSUE THREAD

**Issue by vilemduha** [jayanam/bl_ui_widgets#10]
Disecting what I tried to commit in the pull requests to a few needed functions.

-Need to call these to draw a tooltip or call own functions on entering elements.

-Also would be great to be able to parse keyboard shortcuts - on_keystroke or similar in modal function.

Further needed functions are actually for all mouse interactions - mouse wheel, right-click .

**Comment by jayanam** [comment]
Added methods to register enter exit handlers. For the other descriptions separate issues are required so that things can be tracked and organized in a clean way.

**Comment by vilemduha** [comment]
Thank you for such a fast response!
