### ISSUE TITLE
Ability to disable/enable widgets

### ISSUE THREAD

**Issue by vilemduha** [jayanam/bl_ui_widgets#11]
need to show/hide widgets during operator run, or be able to re-define the layout dynamically.

**Comment by jayanam** [comment]
Please add separate issue for layout re-defintion. For the main issue I will add a new method or property

visible : bool

**Comment by vilemduha** [comment]
Think this can be closed, since .visible was introduced? - Thanks for your support, appreciate it a lot.

**Comment by jayanam** [comment]
Visible property added
