### ISSUE TITLE
Images turn black if the interaction doesn't happen for some time

### ISSUE THREAD

**Issue by vilemduha** [jayanam/bl_ui_widgets#14]
The images drawn still need glTouch() or some other solution to not turn black. An issue was posted for it but was closed.

**Comment by jayanam** [comment]
Ok, can reproduce, was waiting some minutes:-)

**Comment by jayanam** [comment]
Should be fixed now, added the batch creation into draw_image method

**Comment by vilemduha** [comment]
This issue is still happening. 
I fixed it by adding:
```
 # send image to gpu if it isn't there already
if self.__image.gl_load():
    raise Exception()
```
to line 148 in bl_ui_button.py
