### ISSUE TITLE
Button image upper right corner has wrong coordinates. (with solution)

### ISSUE THREAD

**Issue by vilemduha** [jayanam/bl_ui_widgets#15]
bl_ui_button.py - from line 88 should be:

vertices = (
                    (self.x_screen + off_x, y_screen_flip - off_y), 
                    (self.x_screen + off_x, y_screen_flip - sy - off_y), 
                    (self.x_screen + off_x + sx, y_screen_flip - sy - off_y),
                    (self.x_screen + off_x + sx, y_screen_flip - **off_y**))

Currently there's a - off_x on the last coorinate Y which draws the corner offset on non-square offset values.

**Comment by jayanam** [comment]
Fixed with 0.6.4.1
