### ISSUE TITLE
please add more UI widget, such as InputBox\CheckBox

### ISSUE THREAD

**Issue by chuangzhanji** [jayanam/bl_ui_widgets#2]
This project is amazing, using custom UI unit and OpenGL implement UI rather than the inner classes, like Panel\Menu.... This makes the UI more flexiable to creation. But the UI unit is not enough to use, lacking of InputBox\CheckBox\Dropdown\Table, etc. Hope you can realize these UI unit.

**Comment by ReinerBforartists** [comment]
Thanks for your ideas. What you describe sounds like a task for a pie menu. Hmm.

**Comment by jayanam** [comment]
Ok thx, put this into consideration

**Comment by jayanam** [comment]
I close this, Textbox and Checkbox are available
