### ISSUE TITLE
ModuleNotFoundError: No module named '__main__.drag_panel_op

### ISSUE THREAD

**Issue by BerglerAndi** [jayanam/bl_ui_widgets#5]
Im not able to import the modules.

What cant i do?

**Comment by jayanam** [comment]
How do you import and what do you import?

**Comment by BerglerAndi** [comment]
I tried to start __init__.py in blender text-editor and got this error

 File "D:\Blender\Skript\bl_ui_widgets-master\bl_ui_widgets-master\drag_panel.blend\__init__.py", line 15, in <module>
ModuleNotFoundError: No module named '__main__.drag_panel_op'; '__main__' is not a package
Fehler: Python script failed, check the message in the system console

**Comment by jayanam** [comment]
It's an addon, you can import it like any other addon, dont unzip, just
import the zip file in the user preferences.

**Comment by BerglerAndi** [comment]
Oh man,
thank you.. :-)
